import type { Vehicle } from "@/types/vehicle";

/**
 * Hardcoded vehicle data from media folder JSON files
 * Images are served from /media/{carName}/ directory
 */
export const HARDCODED_VEHICLES: Vehicle[] = [
  // Bentley Continental GT
  {
    id: "bentley-continental-gt",
    make: "Bentley",
    model: "Continental GT",
    year: 2019,
    color: "Black",
    status: "Available",
    description: "Luxurious grand tourer with unmatched elegance",
    price: 185000,
    mileage: 5592, // 9000 km = ~5592 miles
    thumbnail: "/media/Bentley/BentleyFrontSide.jpeg",
    image1: "/media/Bentley/BentleyFront.jpeg",
    image2: "/media/Bentley/BentleyBack.jpeg",
    image3: "/media/Bentley/BentleySide.jpeg",
    image4: "/media/Bentley/BentleyFrontDash.jpeg",
    image5: "/media/Bentley/BentleyInternalFront.jpeg",
    regYear: "2019-12",
    makeYear: "2019-03",
    kmDriven: "9000",
    fuelType: "Petrol",
    transmission: "Automatic",
    numOwners: "1st",
    regState: "Maharashtra",
    mileageText: "6.38 kmpl to 12.9 kmpl",
    topSpeed: "335 Km/h",
    marketPrice: "₹3,90,00,000",
    carstreetPrice: "₹3,85,00,000",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  // Lamborghini Revuelto
  {
    id: "lamborghini-revuelto",
    make: "Lamborghini",
    model: "Revuelto 6.5L V12",
    year: 2025,
    color: "Green",
    status: "Available",
    description: "The pinnacle of Italian supercar engineering",
    price: 625000,
    mileage: 155, // 250 km = ~155 miles
    thumbnail: "/media/Lamborghini/LamborghiniFrontSide.jpeg",
    image1: "/media/Lamborghini/LamborghiniFront.jpeg",
    image2: "/media/Lamborghini/LamborghiniSide.jpeg",
    image3: "/media/Lamborghini/LamborghiniDoorsOPen.jpeg",
    image4: "/media/Lamborghini/LamborghiniInternalFront.jpeg",
    image5: "/media/Lamborghini/LamborghiniSteeringWheel.jpeg",
    image6: "/media/Lamborghini/LamborghiniWheel.jpeg",
    regYear: "2026-01",
    makeYear: "2025-12",
    kmDriven: "250",
    fuelType: "Petrol",
    transmission: "Automatic",
    numOwners: "1st",
    regState: "Delhi",
    mileageText: "8.4 to 12 kmpl",
    topSpeed: "350 kmph",
    marketPrice: "₹11,50,00,000",
    carstreetPrice: "₹11,25,00,000",
    createdAt: "2024-03-20T10:00:00Z",
    updatedAt: "2024-03-20T10:00:00Z",
  },
  // Porsche 718 Boxster
  {
    id: "porsche-718-boxster",
    make: "Porsche",
    model: "718 Boxster",
    year: 2017,
    color: "Yellow",
    status: "Available",
    description: "Pure driving pleasure in convertible form",
    price: 72000,
    mileage: 7145, // 11500 km = ~7145 miles
    thumbnail: "/media/Boxster/BoxsterFrontSide.jpeg",
    image1: "/media/Boxster/BoxsterFront.png",
    image2: "/media/Boxster/BoxsterBack.jpeg",
    image3: "/media/Boxster/BoxsterSide.jpeg",
    image4: "/media/Boxster/BoxsterBackSide.jpeg",
    image5: "/media/Boxster/BoxsterSideBack.jpeg",
    regYear: "2018-06",
    makeYear: "2017-12",
    kmDriven: "11500",
    fuelType: "Petrol",
    transmission: "Automatic",
    numOwners: "1st",
    regState: "Haryana",
    mileageText: "9 kmpl",
    topSpeed: "275 kmph",
    marketPrice: "₹95,00,000",
    carstreetPrice: "₹89,00,000",
    createdAt: "2023-11-10T10:00:00Z",
    updatedAt: "2023-11-10T10:00:00Z",
  },
  // Lamborghini Urus
  {
    id: "lamborghini-urus",
    make: "Lamborghini",
    model: "Urus MY19",
    year: 2019,
    color: "White",
    status: "Available",
    description: "The world's first Super Sport Utility Vehicle",
    price: 245000,
    mileage: 11806, // 19000 km = ~11806 miles
    thumbnail: "/media/Urus/UrusFrontSide.jpeg",
    image1: "/media/Urus/UrusFront.png",
    image2: "/media/Urus/UrusBack.jpeg",
    image3: "/media/Urus/UrusSide.jpeg",
    image4: "/media/Urus/UrusBackSide.jpeg",
    image5: "/media/Urus/UrusFrontDash.jpeg",
    regYear: "2020-12",
    makeYear: "2019-12",
    kmDriven: "19000",
    fuelType: "Petrol",
    transmission: "Automatic",
    numOwners: "1st",
    regState: "Himachal Pradesh",
    mileageText: "7.8 kmpl",
    topSpeed: "312",
    marketPrice: "₹3,50,00,000",
    carstreetPrice: "₹3,25,00,000",
    createdAt: "2024-02-05T10:00:00Z",
    updatedAt: "2024-02-05T10:00:00Z",
  },
  // Mercedes-Benz S-Class
  {
    id: "mercedes-s500-maybach",
    make: "Mercedes-Benz",
    model: "S-Class S500 Maybach",
    year: 2014,
    color: "White",
    status: "Available",
    description: "The epitome of luxury and comfort",
    price: 95000,
    mileage: 35731, // 57500 km = ~35731 miles
    thumbnail: "/media/Mercedes/MercedesFrontSide.jpeg",
    image1: "/media/Mercedes/MercedesFrontSideZoom.jpeg",
    image2: "/media/Mercedes/MercedesFrontDash.jpeg",
    image3: "/media/Mercedes/MercedesInternalBack.jpeg",
    image4: "/media/Mercedes/MercedesRoof.jpeg",
    regYear: "2015-12",
    makeYear: "2014-12",
    kmDriven: "57500",
    fuelType: "Petrol",
    transmission: "Automatic",
    numOwners: "1st",
    regState: "Maharashtra",
    mileageText: "8.5-10 kmpl",
    topSpeed: "250 kmph",
    marketPrice: "₹26,00,000",
    carstreetPrice: "₹23,75,000",
    createdAt: "2023-09-15T10:00:00Z",
    updatedAt: "2023-09-15T10:00:00Z",
  },
  // Rolls Royce Ghost
  {
    id: "rolls-royce-ghost",
    make: "Rolls Royce",
    model: "Ghost Series 2",
    year: 2015,
    color: "Blue",
    status: "Available",
    description: "Ultimate luxury meets effortless performance",
    price: 165000,
    mileage: 19263, // 31000 km = ~19263 miles
    thumbnail: "/media/Ghost/GhostFrontSide.jpeg",
    image1: "/media/Ghost/GhostFront.jpeg",
    image2: "/media/Ghost/GhostDoorsOpen.jpeg",
    image3: "/media/Ghost/GhostEngine.jpeg",
    regYear: "2015-12",
    makeYear: "2015-07",
    kmDriven: "31000",
    fuelType: "Petrol",
    transmission: "Automatic",
    numOwners: "1st",
    regState: "Puducherry",
    mileageText: "9.8 kmpl",
    topSpeed: "250 Km/h",
    marketPrice: "₹3,80,00,000",
    carstreetPrice: "₹3,60,00,000",
    createdAt: "2023-12-01T10:00:00Z",
    updatedAt: "2023-12-01T10:00:00Z",
  },
  // Land Rover Defender
  {
    id: "land-rover-defender",
    make: "Land Rover",
    model: "Defender 5.0 V8",
    year: 2024,
    color: "Black",
    status: "Available",
    description: "Legendary capability meets modern luxury",
    price: 125000,
    mileage: 6835, // 11000 km = ~6835 miles
    thumbnail: "/media/Defender/DefenderFrontSide.jpeg",
    image1: "/media/Defender/DefenderFront.jpeg",
    image2: "/media/Defender/DefenderBack.jpeg",
    image3: "/media/Defender/DefenderSide.jpeg",
    image4: "/media/Defender/DefenderBackSide.jpeg",
    image5: "/media/Defender/DefenderFrontDash.jpeg",
    regYear: "2024-12",
    makeYear: "2024-08",
    kmDriven: "11000",
    fuelType: "Petrol",
    transmission: "Automatic",
    numOwners: "1st",
    regState: "Himachal Pradesh",
    mileageText: "6.8 kmpl",
    topSpeed: "240 Km/h",
    marketPrice: "₹1,80,00,000",
    carstreetPrice: "₹1,68,00,000",
    createdAt: "2024-03-25T10:00:00Z",
    updatedAt: "2024-03-25T10:00:00Z",
  },
];
